Repository LT-Students/DigitalOffice-RightsService, pull requests merged in 2021-07, with the labels that each got.

#27 change class to record
  src/RightsService.Models.Dto/Models/RoleInfo.cs
  src/RightsService.Models.Dto/Models/UserInfo.cs
  src/RightsService.Models.Dto/Requests/CreateRoleRequest.cs
  src/RightsService.Models.Dto/Responses/FindResponse.cs
  src/RightsService.Models.Dto/Responses/RightResponse.cs
  src/RightsService.Models.Dto/Responses/RoleResponse.cs
Labels: enhancement

#28 fix get users data endpoint
  src/RightsService.Models.Dto/Configurations/RabbitMqConfig.cs
  src/RightsService/appsettings.json
Labels: bug

#29 add change user role consumer
  Common.Configurations.targets
  src/RightsService.Broker/Consumers/AccessCollectionValidatorConsumer.cs
  src/RightsService.Broker/Consumers/AccessValidatorConsumer.cs
  src/RightsService.Broker/Consumers/ChangeUserRoleConsumer.cs
  src/RightsService.Business/Commands/Role/FindRolesCommand.cs
  src/RightsService.Business/Commands/Role/GetRoleCommand.cs
  src/RightsService.Data.Provider.MsSql.Ef/Migrations/20210625000000_AddRolesTables.cs
  src/RightsService.Data.Provider.MsSql.Ef/Migrations/20210706091500_RemoveColumsFromUsersTable.cs
  src/RightsService.Data/Interfaces/IRightRepository.cs
  src/RightsService.Data/Interfaces/IUserRepository.cs
  src/RightsService.Data/RightRepository.cs
  src/RightsService.Data/UserRepository.cs
  src/RightsService.Models.Db/DbUser.cs
  src/RightsService.Models.Dto/Configurations/RabbitMqConfig.cs
  src/RightsService/Startup.cs
  src/RightsService/appsettings.json
  test/RightsService.Broker.UnitTests/Consumers/AccessCollectionValidatorConsumerTests.cs
  test/RightsService.Business.UnitTests/Commands/Role/CreateRoleCommandTests.cs
Labels: enhancement

#31 fix github actions
  .github/workflows/main.yml
Labels: documentation

#30 add get user roles consumer
  Common.Configurations.targets
  src/RightsService.Broker/Consumers/GetUserRolesConsumer.cs
  src/RightsService.Data/Interfaces/IUserRepository.cs
  src/RightsService.Data/UserRepository.cs
  src/RightsService.Models.Dto/Configurations/RabbitMqConfig.cs
  src/RightsService/Startup.cs
  src/RightsService/appsettings.json
Labels: enhancement

#34 fix pagination
  src/RightsService.Data/RoleRepository.cs
  test/RightsService.Data.UnitTests/RoleRepositoryTests.cs
Labels: bug

#35 docs/change_actions
  .github/workflows/main.yml
Labels: documentation

#37 Feature/fix cors
  src/RightsService/Startup.cs
Labels: enhancement

#38 update models version
  Common.Configurations.targets
  test/RightsService.Mappers.UnitTests/UserInfoMapperTests.cs
Labels: enhancement
